
package visual;

import logica.Usuario;
import basedatos.conexionBD;

public class CrearCuenta extends javax.swing.JFrame {

    conexionBD objBD = null;
    Usuario objUs = null;
    
    public CrearCuenta() {
        objUs = new Usuario();
        objBD = new conexionBD();
        initComponents();
    }

    /*public CrearCuenta() {
        initComponents();
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotonesInicio = new javax.swing.JPanel();
        btnRegistrarse = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        pnlInscribirse = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlRegistroDatos = new javax.swing.JPanel();
        lblRegistro = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmarP = new javax.swing.JLabel();
        txtfUser = new javax.swing.JTextField();
        txtfEmail = new javax.swing.JTextField();
        pswrfPassword = new javax.swing.JPasswordField();
        pswrfConfirma = new javax.swing.JPasswordField();
        lblObligatorio = new javax.swing.JLabel();
        lblObligatorio1 = new javax.swing.JLabel();
        lblObligatorio2 = new javax.swing.JLabel();
        lblObligatorio3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrarse.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        pnlBotonesInicio.add(btnRegistrarse);

        btnIniciarSesion.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnIniciarSesion.setText("Iniciar sesion");
        pnlBotonesInicio.add(btnIniciarSesion);

        getContentPane().add(pnlBotonesInicio, java.awt.BorderLayout.PAGE_START);

        pnlInscribirse.setLayout(new java.awt.BorderLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlInscribirse.add(jButton1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlInscribirse, java.awt.BorderLayout.PAGE_END);

        lblRegistro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRegistro.setText("Ingresa tu informacion");

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUser.setText("Usuario:");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setText("Password:");

        lblConfirmarP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConfirmarP.setText("Confirma tu Password:");

        lblObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        lblObligatorio.setText("*");

        lblObligatorio1.setForeground(new java.awt.Color(255, 0, 0));
        lblObligatorio1.setText("*");

        lblObligatorio2.setForeground(new java.awt.Color(255, 0, 0));
        lblObligatorio2.setText("*");

        lblObligatorio3.setForeground(new java.awt.Color(255, 0, 0));
        lblObligatorio3.setText("*");

        javax.swing.GroupLayout pnlRegistroDatosLayout = new javax.swing.GroupLayout(pnlRegistroDatos);
        pnlRegistroDatos.setLayout(pnlRegistroDatosLayout);
        pnlRegistroDatosLayout.setHorizontalGroup(
            pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblRegistro))
                    .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail)
                            .addComponent(lblUser)
                            .addComponent(lblPassword)
                            .addComponent(lblConfirmarP))
                        .addGap(44, 44, 44)
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtfEmail)
                            .addComponent(pswrfPassword)
                            .addComponent(pswrfConfirma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObligatorio)
                            .addComponent(lblObligatorio1)
                            .addComponent(lblObligatorio2)
                            .addComponent(lblObligatorio3))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlRegistroDatosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblConfirmarP, lblEmail, lblPassword, lblUser});

        pnlRegistroDatosLayout.setVerticalGroup(
            pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblRegistro)
                .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(txtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(pswrfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfirmarP)
                            .addComponent(pswrfConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblObligatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblObligatorio1)
                        .addGap(12, 12, 12)
                        .addComponent(lblObligatorio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblObligatorio3)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pnlRegistroDatosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pswrfConfirma, pswrfPassword, txtfEmail, txtfUser});

        pnlRegistroDatosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblObligatorio, lblObligatorio1, lblObligatorio2, lblObligatorio3});

        getContentPane().add(pnlRegistroDatos, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(objUs != null){
            objUs.setUser(txtfUser.getText());
            objUs.setEmail(txtfEmail.getText());
            char[] password = pswrfConfirma.getPassword();
            String pswr = new String(password);
            objUs.setPassword(pswr);

            objBD.abrirConexion();
            objBD.insertarUser(objUs);
            objBD.cerrarConexion();
        } else {
            System.out.println("objUs esta nulo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblConfirmarP;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblObligatorio;
    private javax.swing.JLabel lblObligatorio1;
    private javax.swing.JLabel lblObligatorio2;
    private javax.swing.JLabel lblObligatorio3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlBotonesInicio;
    private javax.swing.JPanel pnlInscribirse;
    private javax.swing.JPanel pnlRegistroDatos;
    private javax.swing.JPasswordField pswrfConfirma;
    private javax.swing.JPasswordField pswrfPassword;
    private javax.swing.JTextField txtfEmail;
    private javax.swing.JTextField txtfUser;
    // End of variables declaration//GEN-END:variables
}
